id: AD78624E6
title: Guru Yoga of Milarepa Shepa Dorje for Daily Practice
type: translation
pechas:
- I70886D09
- I9D6EBCB7
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:02:10.273311
  last_modified_at: 2023-01-04 13:02:10.273318
  collections:
  - Milarepa Series
  - Works of Tibetan Masters
alignment_to_base:
  I70886D09/6327: 773B
  I9D6EBCB7/4885: 773B
